package direct

// Blocked RSA placements — mobile games, entertainment apps, junk traffic (407 entries).
var blockedPlacements = []string{
	"air.bestescapegames.hiddengame", "air.com.bestescapegames.escapefearhouse2",
	"air.com.escapefearhouse", "at.ner.lepsworld2", "biz.bdgroup.wordbyword",
	"bsmusic.free", "bubbleshooter.puzzle", "bubbleshooter.orig",
	"block.puzzle.sudoku.free.game.classic.offline", "book-online.com.ua",
	"com.7thg.flashlight", "com.aa2g1ltd.popitmaster3dfidgettoyssimpledimple",
	"com.aaaudi.wordmaker", "com.adme",
	"com.agedstudio.board.game.dominoes", "com.agedstudio.card.spider.solitaire",
	"com.aif.aifkitchen", "com.alfa.bubble_birds2.gplay",
	"com.almondstudio.artduel", "com.almondstudio.crossword",
	"com.almondstudio.findwordsoup", "com.almondstudio.riddles",
	"com.almondstudio.wordbyword", "com.amberfog.vkfree",
	"com.andevapps.ontv", "com.android.browser",
	"com.andreizubarev.vkmessenger", "com.andreyrebrik.klondike",
	"com.antistress.oddly.satisfying.Antistress", "com.anyreads.patephone",
	"com.aottanks.thegrandauto", "com.apalon.myclock",
	"com.apalon.myclockfree", "com.apalon.wallpapers",
	"com.apalonapps.calcfree", "com.apalonapps.livewallpapersfree",
	"com.apalonapps.smartalarmfree", "com.apalonapps.wlf",
	"com.appsomniacs.da2", "com.appteka.sportexpress",
	"com.appolo13.stickmandrawanimation", "com.arcsoft.Perfect365",
	"com.ascellamobile.musicloudfree", "com.asd.europaplustv",
	"com.askfm", "com.bakiromarov.boxingphysics",
	"com.bandagames.mpuzzle.gp", "com.banderlogiapps.hd",
	"com.Bearoff.CSS", "com.bigduckgames.flow",
	"com.bonbeart.doors", "com.bonbeart.doors3",
	"com.bonbeart.doorsseasons.part1", "com.bonbeart.doorsseasons.part2",
	"com.botiki.logika3", "com.calfordcn.gu",
	"com.camerasideas.instashot", "com.cg.fanofguns",
	"com.choofun.myworldfree", "com.cleanmaster.mguard",
	"com.cleanmaster.security", "com.cloudycastlegames.wordline",
	"com.coloring.color.number.ios", "com.cootek.smartinputv5",
	"com.cootek.smartinputv5.freeoem", "com.cootek.smartinputv5.oem",
	"com.craftgames.plntcrft", "com.crazylight.photoscanner.age",
	"com.creativem.geneticsfull", "com.creativemobile.dragracing",
	"com.crone.worldofskins", "com.csasecurity.app",
	"com.cyberlink.youperfect", "com.deendev.ugadairossiiskiibrend",
	"com.deendev.ugadairossiiskiifk", "com.detectunfollowers",
	"com.devexpert.weather", "com.devgame.cats.sea.adventure.kids.treasure.hunt.quest",
	"com.devgame.kidecatssupermarket", "com.devgame.energychain",
	"com.digidust.elokence.akinator.freemium", "com.dmitriygavrilov.thegrandauto",
	"com.dmitry.social.nets.vkontakevkmini", "com.droid27.digitalclockweather",
	"com.droid27.transparentclockweather", "com.e7mobile.perfectswing",
	"com.easybrain.sudoku.android", "com.echomoscow.EchoMsk",
	"com.edadeal.android", "com.emoji.keyboard.touchpal",
	"com.emperorlab.pddtestsquiz", "com.enchantedcloud.photovault",
	"com.enrasoft.scratchthat.logoquiz", "com.evermatch",
	"com.evogames.oligarch2", "com.fingersoft.failhard",
	"com.fingersoft.hillclimb", "com.fingersoft.hillclimbracing",
	"com.firsttouch.ftsb", "com.firsttouch.story",
	"com.firsttouchgames.score", "com.firsttouchgames.story",
	"com.flashmobgames.airbubbles", "com.fmarzana.vdlfree2",
	"com.football.real.gol", "com.fugo.wow",
	"com.fugo.wowguru", "com.fugo.wowsearch",
	"com.fullreader", "com.gamecircus.prizeclaw",
	"com.gameloft.android.anmp.gloftgghm", "com.gameloft.android.anmp.gloftm5hm",
	"com.games.joinblocks", "com.games.makewords2",
	"com.gangtheftautoinception", "com.gemteam.stickerpackstg",
	"com.gemteam.trmpclient", "com.gipnetix.doorsrevenge",
	"com.gipnetix.dr", "com.gismart.drum.pads.machine",
	"com.glorygame.tileblast", "com.gongobot.gramazeka",
	"com.gongobot.repost", "com.gongobot.vkboost",
	"com.gregorioapps.stfree", "com.grindrapp.android",
	"com.grydmitrij.ticketpdddemo", "com.gta.gangtheftauto",
	"com.havos.codewordunlimited", "com.hb.dialer.free",
	"com.hornet.android", "com.how.to.draw.hair",
	"com.hqin.headsup.holdem", "com.hypercarrot.giantrush",
	"com.hyperionics.avar", "com.idownloaderapp.idl2free",
	"com.igoodnewgames.airlines2", "com.igoodnewgames.jewels",
	"com.ihappydate", "com.imo.android.imoim",
	"com.imo.android.imoimbeta", "com.imo.android.imoimhd",
	"com.imoimiphone.ios", "com.indie.bustime",
	"com.indigokids.mim", "com.infoshell.recradio",
	"com.iosgames.yesno", "com.istudioinc2012.bubbletrouble",
	"com.ivymaze.puzzlejigsaw", "com.izmo.onlinekafatopu",
	"com.jagplay.client.android.app.durak", "com.jagplay.client.android.app.thousand.hd",
	"com.jewels.gems.android", "com.jsdev.instasize",
	"com.k17.millionaire", "com.k17.viselitsa2",
	"com.karmangames.solitaire", "com.karmangames.spider",
	"com.keplerians.evilnun", "com.keplerians.evilnun2",
	"com.keplerians.icescream", "com.keplerians.icescreamtwo",
	"com.keplerians.icescream4", "com.ketchapp.knifehit",
	"com.kharraz-developers.stw3free", "com.KrakerStudio.ArrowsWave",
	"com.krutigrama.games.android.words.collector", "com.kumbralyov.keywords.keywords",
	"com.kwalee.citybuilder", "com.lander.hello",
	"com.lawson.poke", "com.lenta.magazine.release",
	"com.leopoldoapps.stfree", "com.liberty.auto",
	"com.lightside.caseopener", "com.lightside.caseopener2",
	"com.linkedbit.megasudokufree", "com.lockwoodpublishing.avakinlife",
	"com.loopgamestudio.adsmoney", "com.loopgamestudio.myapplication",
	"com.loopgamestudio.vmoney", "com.lunappstudio.wordomaze",
	"com.mandarin.android", "com.marulgames.wordsurf",
	"com.maybeyou", "com.mega_mc.mcpeskinstudio",
	"com.mega_mc.serverslistforminecraftpe", "com.merigotech.fillwords",
	"com.metadesign.ruauto", "com.miniclip.agar.io",
	"com.miui.videoplayer", "com.mobiloids.trueorfalserussian",
	"com.mobiloids.wordmixrussian", "com.mobiray.caseopener",
	"com.mocomediallc.fastfriend", "com.modsforminecraftpe.installer",
	"com.muscle.rush", "com.my.defense",
	"com.myfitnesspal.android", "com.nanobyte.bigfoot.hunting.online",
	"com.narde.backgammon.game", "com.nektome.chatruletka.voice",
	"com.nektome.talk", "com.neptune.ludo",
	"com.nevogames.iwitch", "com.newsstand.dating",
	"com.ninegag.android.app", "com.nirkof.starpas",
	"com.nirkof.taro", "com.oas_dev.doors_world_of_history_2",
	"com.oki.phonenew", "com.onecwireless.mahjong3.google.free",
	"com.opera.browser", "com.opera.mini.native",
	"com.openmygame.games.android.crosswordru",
	"com.openmygame.games.android.fillwords",
	"com.openmygame.games.android.jigsawpuzzle",
	"com.openmygame.games.android.scanwords",
	"com.openmygame.games.android.wordpizza",
	"com.openmygame.games.android.wordsearchsea",
	"com.openmygame.games.kr.client", "com.openmygame.games.kr.ios.krclient",
	"com.openmygame.magicwordsearch", "com.orionsgames.mahjong",
	"com.outfit7.herodash", "com.outfit7.mytalkingangelafree",
	"com.outfit7.mytalkingtom2", "com.outfit7.mytalkingtomfree",
	"com.outfit7.mytalkinghank", "com.outfit7.mytalkingangela2",
	"com.outfit7.talkingangelafree", "com.outfit7.talkingben",
	"com.outfit7.talkingtom2free", "com.outfit7.talkingtomgoldrun",
	"com.outfit7.tomlovesangelafree", "com.outerminds.tubular",
	"com.owentech.sleepybabylite", "com.p74.player",
	"com.perchikapps.vmusic", "com.perm.kate",
	"com.pinpinteam.rockcrawling", "com.pixel.art.coloring.color.number",
	"com.pixelduck.ru4pics1word", "com.plabs.planetofc",
	"com.playstrom.dop2", "com.playstrom.dop4",
	"com.prestigio.ereader", "com.promt.pmtappfree",
	"com.promt.translaterufree", "com.pronetis.ironball2",
	"com.ptolkachev.feelwordsdruidsnotes", "com.puzzlefun.blockgame",
	"com.qoni.guesstheiranswer", "com.rambler.horoscopes",
	"com.rbtdigital.battery-life", "com.redeyes.pokegoguideru",
	"com.RedLineGames.Game49", "com.renualsoftware.minecraftpe.minecraftpeservers",
	"com.rexplayer.app", "com.rezustadevs.ytp",
	"com.ringtonesapp", "com.rkrebs.vdlfree",
	"com.romant.image", "com.rugion.RugionNews",
	"com.rusdev.pid", "com.rushgames.giantcolor",
	"com.s-g-i.edadeal", "com.scanword.journal",
	"com.shadowbiz.semechki", "com.spcards.cards2",
	"com.sportexpress.ipad", "com.sportexpress.iphone",
	"com.sprakelsoftug.colormemo", "com.springwalk.mediaconverter",
	"com.stack.booklib2", "com.streu.wordsinword",
	"com.supercraft.hd", "com.surpax.ledflashlight.panel",
	"com.swiftsoft.anixart", "com.tanksblitz",
	"com.tatwipe.hobo", "com.teamtol.livedota",
	"com.tellurionmobile.realmcraft", "com.tesseractmobile.solitairefreepack",
	"com.therefik.skyland", "com.thousandcardgame.android.huawei",
	"com.tigrido.color6", "com.tomato.pasbayan",
	"com.topface.topface", "com.tripledot.woodoku",
	"com.tunein.tuneinradio", "com.turbo.stars",
	"com.vanikin.knowwordquiz", "com.veraxen.jigsawpuzzlescollectionhd",
	"com.vgs.fidgetcubebuttons.antistress.calming", "com.vicman.cartoon",
	"com.videoplayer.videoplayerforyoutubefree", "com.vincentb.mobcontrol",
	"com.vitastudio.mahjong", "com.wallpapers.ru",
	"com.waplog.social", "com.wethole.ghpme",
	"com.wgpslokator", "com.whatsapplock",
	"com.whisperarts.kids.breastfeeding", "com.wildec.dating.meet4u",
	"com.winwingames.scanwords", "com.wordgame.ugadaiedu",
	"com.wpochemutelefontormozit", "com.wskinforslitherio",
	"com.ximad.puzzlesmagic", "com.yandex.alicekit.demo",
	"com.yandex.launcher", "com.zeninfun.tileblast",
	"com.zeninfun.tileconnect", "com.zeroninetyninestudio.artwallpapers",
	"com.zifun.bubble", "com.zigzag_mobile.skorolek",
	"com.zm.watersort", "com.zynga.looney",
	"cz.psc.android.kaloricketabulky", "eu.targetworks.solitaire",
	"fm.ask.askfm", "gdz.ru",
	"ilive.com.ua", "islandscapes.puzzle.game",
	"me.incrdbl.android.wordbyword", "net.zedge.android",
	"online-knigi.com.ua", "org.aastudio.games.backgammon",
	"org.aastudio.games.longnards", "org.speedspot.speedspotspeedtest",
	"real.piano.free", "ru.autoschooljack.android",
	"ru.bestfeeds.pro.vk-feed", "ru.bestfeeds.vk-feed",
	"ru.brothersappsandgames.kittenrescuepinpull",
	"ru.brothersappsandgames.superpopitsimulatorasmrrelax",
	"ru.cmlt", "ru.cn.tv",
	"ru.flirchi.android", "ru.gde-fon.com",
	"ru.gimeney.net", "ru.hellomagazine.com",
	"ru.iobit.com", "ru.iosgames.auto",
	"ru.iosgames.countries", "ru.kanzitdinov.supervkapp2",
	"ru.kefline.com", "ru.kev163rus.thefutureguy",
	"ru.livelib.client", "ru.loveplanet.app",
	"ru.medkrug.kbrapp", "ru.mobiledimension.kbr",
	"ru.motorsport.com", "ru.msn.com",
	"ru.ngs.news", "ru.ngs.ngs",
	"ru.onlinemschool.com", "ru.otzyv.com",
	"ru.publishing1c.ivan_free", "ru.rambler.horoscopes",
	"ru.rusmarket.com", "ru.ruxlab.get10.free",
	"ru.softinvent.yoradio", "ru.st1ng.vk",
	"ru.subprogram.guitarsongs", "ru.thousandcardgame.android",
	"ru.ucoin.net", "ru.wit.kefir",
	"se.feomedia.qkrussia", "se.feomedia.quizkampen.ru.lite",
	"vost.com.ua", "game.yandex.ru",
	"game.maddex.jump", "gameoko.ru",
	"gamesisart.ru", "showgamer.com",
	"game-tips.ru", "gamer-mods.ru",
	"landofgames.ru", "hypergames.top",
	"sdamgia.ru", "shuteikacom.ru",
	"etagi.com",
	// Ad networks
	"Smaato", "MobFox", "MoPub", "BidSwitch", "Inner-active", "AdsNative",
	// Original partial list additions
	"com.altaworks.koala", "com.am15.ucolor",
	"com.andi.tetris", "com.anstudio.puzzlejigsaw",
	"com.app.go.puzzle.game", "com.arcticfoxstudio.worldcrafters",
	"com.azurgames.stackball", "com.babelgames.flood",
	"com.belka.SkiSafari2.gp", "com.bivrostgames.word",
	"com.boombitgames.crossyroad", "com.budgestudios.MyLittlePonyPocketPonies",
	"com.byril.smashhit", "com.caverock.squarequote",
	"com.cellufun.myhorse", "com.cleverapps.transport",
	"com.cleverapps.wordbubbles", "com.cloudteam.subway",
	"com.cute.satellite", "com.diamondapps.crocword",
	"com.digiflame.classic.games.free", "com.dts.freefireth",
	"com.eightfit.app", "com.estoty.coloringbook",
	"com.ezjoy.mahjong.android", "com.game.colorball.sort",
	"com.game.logicball", "com.gameberry.ludo",
	"com.gametion.ludoking", "com.gardenscapes.rk",
	"com.grandgames.nonograms", "com.gz.badminton.android",
	"com.happyfi.cakincrush", "com.heyzap.helium",
	"com.hi.crossword", "com.idreamsky.monopoly.tycoon",
	"com.innogames.foeandroid", "com.iplaystudio.brain.test",
	"com.ivangraphics.findword", "com.jacktor.textquote",
	"com.joymax.windrunner", "com.kakaogames.moonlight",
	"com.king.candycrush4", "com.king.candycrushsodasaga",
	"com.kitkagames.fallball", "com.leodesol.games.sudoku",
	"com.loop.games.block", "com.lotgames.word.connect",
	"com.lrt.brainUp", "com.ma.crossword",
	"com.magiclab.towerwar", "com.mahjong.game.puzzle",
	"com.make.sticker.diy", "com.metatr0n.brain.test.tricky.puzzles",
	"com.mobilegames.mahjong.butterfly", "com.mpl.androidapp",
	"com.musemaze.puzzle.coloring", "com.nenoff.doodlejump",
	"com.noodlecake.altosadventure", "com.notinkhair.hair",
	"com.omniblocks.crush", "com.pandascore.score",
	"com.pandapuzzlegames.freecrossword", "com.playdots.twodots",
	"com.playgendary.aquapark", "com.playgendary.kickthebuddy",
	"com.playgendary.tank", "com.puzzle.jigsaw.collection",
	"com.puzzle.world.number", "com.quartzo.dominos",
	"com.random_logic.sudoku", "com.rottzgames.wod",
	"com.rush.race.endless", "com.scanword.mega.rw",
	"com.secondgear.puzzledom", "com.simple.sudoku",
	"com.snailgamesusa.ark", "com.softick.android.solitaire.klondike",
	"com.sportstechnologies.quiz.cricket",
	"com.squareenixmontreal.hitmansniperassassins",
	"com.supercell.brawlstars", "com.supercell.clashroyale",
	"com.tencent.ig", "com.tnbstudios.block.puzzle",
	"com.tutotoons.app.popgirl", "com.wetcat.creativecats",
	"com.wordgame.puzzle.board.en", "com.wordgames.word.connect.find",
	"com.wordscapes", "com.yandex.games",
	"com.zeka.games.sudoku", "de.mobilityware.solitaire",
	"de.wetteronline.wetterapp", "dnevnik.ru",
	"games.durak.online", "io.voodoo.crowdcity",
	"io.voodoo.paper2", "mahjong.butterfly.match.garden",
	"me.flavor.recipes", "net.gameboss.brainpuzzle",
	"net.peakgames.toon", "org.nicehorse.Race",
	"pool.billiards.city", "ru.4pda.client",
	"ru.cardsmobile.stocard", "ru.eda.kitchen",
	"ru.gismeteo.gismeteo", "ru.myheat.myheat",
	"word.crossword.puzzle.games", "word.find.word.search",
	"www.russiafishing.ru",
}

// Sitelink library organized by theme.
var sitelinkLibrary = map[string][]sitelinkSet{
	"вторичка": {
		{Theme: "вторичка", Placement: "поиск", Source: "Тюмень", Links: []sitelink{
			{"Купить квартиру", "Большая база квартир города", "/realty/"},
			{"Квартиры со скидками", "Сниженные цены от проверенных собственников", "/realty/?old_price_min=price"},
			{"Однокомнатные", "Однушки от проверенных собственников", "/realty/odnokomnatnye-kvartiry/"},
			{"Двухкомнатные", "Двушки с фото и планировками", "/realty/dvuhkomnatnye-kvartiry/"},
			{"С ремонтом", "Квартиры с готовым ремонтом", "/realty/?keep[]=cosmetic&keep[]=design&keep[]=good"},
			{"Без ремонта", "Квартиры под свой ремонт", "/realty/?keep[]=need&keep[]=well_black&keep[]=black"},
			{"Гарантия безопасности", "Юридическая проверка каждой сделки", "/t/security/"},
			{"Онлайн услуги", "Купить недвижимость не выходя из дома", "/lp/remote-services/"},
		}},
		{Theme: "вторичка", Placement: "рся", Source: "Тюмень", Links: []sitelink{
			{"Проверенные объекты", "Выгодные условия по ипотеке", "/realty/?old_price_min=price&seller[]=owner&type[]=1"},
			{"Гарантия безопасности", "Покупка недвижимости без риска", "/t/security/"},
			{"Скидки от собственников", "Сниженные цены от проверенных собственников", "/realty/?old_price_min=price&seller[]=owner&type[]=1"},
			{"Одобрение ипотеки за 3 мин", "Одобрение выше на 20%, чем в банке", "/realty/?old_price_min=price&seller[]=owner&type[]=1"},
			{"Каталог", "Полная база объектов от проверенных собственников", "/realty/?old_price_min=price&seller[]=owner&type[]=1"},
			{"1-комнатные", "Однокомнатные от проверенных собственников", "/realty/?old_price_min=price&rooms[]=1"},
			{"2-комнатные", "Двухкомнатные от проверенных собственников", "/realty/?old_price_min=price&rooms[]=2"},
			{"3-комнатные", "Трехкомнатные от проверенных собственников", "/realty/?old_price_min=price&rooms[]=3"},
		}},
	},
	"новостройки": {
		{Theme: "новостройки", Placement: "поиск", Source: "Тюмень", Links: []sitelink{
			{"Все ЖК", "Покупайте жилье в новых ЖК без комиссии", "/zastr/"},
			{"Без комиссии", "Новостройки без комиссии по ценам от застройщиков", "/zastr/"},
			{"Одобрим ипотеку за 3 минуты", "Одобрение выше на 20%, чем в банке", "/ipoteka/zastr/"},
			{"Рассрочка 0%", "Подборка квартир в новых ЖК", "/zastr/?installment=!"},
			{"Скидки от застройщиков", "Персональные условия по покупке", "/zastr/"},
			{"Отделка на выбор", "Узнайте подробности про ЖК", "/zastr/"},
			{"Юридическое сопровождение", "Подборка по вашим параметрам", "/zastr/"},
			{"Сопровождение сделок", "Бесплатное сопровождение первичной недвижимости", "/zastr/"},
		}},
		{Theme: "новостройки", Placement: "поиск,рся", Source: "Ростов", Links: []sitelink{
			{"1-комнатные квартиры", "Большой выбор однокомнатных от застройщика", "/zastr/?rooms[]=1&studio[]=false"},
			{"2-комнатные квартиры", "Большой выбор двухкомнатных от застройщика", "/zastr/?rooms[]=2&studio[]=false"},
			{"3-комнатные квартиры", "Большой выбор трехкомнатных от застройщика", "/zastr/?rooms[]=3&studio[]=false"},
			{"Квартиры-студии", "Студии от застройщиков", "/zastr/studii/"},
			{"Сданные ЖК", "Готовые к заселению жилые комплексы", "/zastr/dom-sdan/"},
			{"Успейте по семейной ипотеке", "Лимиты по семейной ипотеке могут исчерпаться", "/ipoteka/family-mortgage/"},
		}},
	},
	"загородка": {
		{Theme: "загородка", Placement: "поиск", Source: "Тюмень", Links: []sitelink{
			{"Вся загородная недвижимость", "Дома, дачи, участки, коттеджи", "/realty_out/"},
			{"Гарантия безопасности", "Юридическая проверка каждой сделки", "/t/security/"},
			{"Онлайн услуги", "Купить недвижимость не выходя из дома", "/lp/remote-services/"},
			{"Дома и коттеджи", "Загородная недвижимость с фото", "/realty_out/doma/"},
			{"Дачи и участки", "Земельные участки с коммуникациями", "/realty_out/dachnye-uchastki/"},
		}},
		{Theme: "загородка", Placement: "поиск,рся", Source: "Ростов", Links: []sitelink{
			{"Юридическое сопровождение", "Гарантируем безопасность сделки своими деньгами", "/t/security/"},
			{"Дачи", "Дачи и дачные участки по выгодным ценам", "/realty_out/dachnye-uchastki/"},
			{"Коттеджи", "Коттеджи в пределах и за пределами города", "/realty_out/cottage/"},
			{"Земельные участки", "Земельные участки в черте города и пригороде", "/realty_out/zemelnye-uchastki/"},
			{"Коттеджные поселки", "Все коттеджные поселки с ценами на сайте", "/newcottages/"},
			{"В черте города", "Объекты загородной недвижимости в черте города", "/realty_out/?incity=true"},
			{"Контакты", "Звоните нам в любое время, мы на связи 24/7", "/contacts/"},
		}},
	},
	"аренда": {
		{Theme: "аренда", Placement: "поиск", Source: "Краснодар", Links: []sitelink{
			{"Квартиры", "Большая база квартир в аренду", "/realty_rent/"},
			{"1-комнатные", "Актуальные предложения аренды однокомнатных", "/realty_rent/?rooms[]=1"},
			{"2-комнатные", "Актуальные предложения аренды двухкомнатных", "/realty_rent/?rooms[]=2"},
			{"3-комнатные", "Актуальные предложения аренды трехкомнатных", "/realty_rent/?rooms[]=3"},
			{"Студии", "Все объявления аренды квартир-студий", "/realty_rent/"},
			{"Получить подборку", "Получите подбор в 2 клика", "/realty_rent/"},
			{"Проконсультироваться", "Бесплатные консультации по аренде", "/realty_rent/"},
			{"Контакты", "Адрес офиса и телефоны для быстрой связи", "/contacts/"},
		}},
	},
	"ипотека": {
		{Theme: "ипотека", Placement: "поиск,рся", Source: "Тюмень", Links: []sitelink{
			{"Одобрение выше на 20%", "Оставьте заявку на сайте", "/ipoteka/"},
			{"Ипотечные программы", "Выберите подходящую на сайте", "/ipoteka/"},
			{"Сниженные ставки", "Скидки от банков-партнеров", "/ipoteka/"},
			{"Семейная ипотека", "Купите квартиру или дом по льготной ставке", "/ipoteka/family-mortgage/"},
			{"Ипотека для IT", "Купите квартиру или постройте дом по льготной ставке", "/ipoteka/it-workers/"},
			{"Калькулятор ипотеки", "Рассчитайте платёж онлайн", "/ipoteka/calculator/"},
			{"Контакты", "Круглосуточно отвечаем на ваши вопросы", "/contacts/"},
		}},
	},
	"коммерческая": {
		{Theme: "коммерческая", Placement: "поиск,рся", Source: "Тюмень", Links: []sitelink{
			{"Без комиссии", "Для покупателя и арендатора", "/commerce/?orderId=priceasc"},
			{"Объекты в рассрочку", "Рассрочка от собственника", "/commerce/?installment_owner[]=!&orderId=priceasc"},
			{"Коммерческая ипотека", "Ипотека со скидкой – 0.7% для клиентов Этажей", "/ipoteka/commerce/"},
			{"Гарантия безопасности сделки", "Проверка объектов и всех участников сделки", "/t/security/"},
			{"Полное сопровождение", "Юридическое и финансовое сопровождение", "/commerce/?orderId=priceasc"},
			{"Коммерция от застройщиков", "Помещения различной квадратуры под любые нужды", "/commerce/?ticket_seller[]=builder"},
			{"Недвижимость с арендатором", "Более 500 объектов с действующим арендатором", "/commerce/?renter_exist=t&orderId=priceasc"},
			{"Готовые бизнесы", "Покупка бизнеса под ключ от 150 000 ₽", "/commerce/?type[]=22&orderId=priceasc"},
		}},
	},
	"агентство": {
		{Theme: "агентство", Placement: "поиск,рся", Source: "Омск", Links: []sitelink{
			{"Вторичка", "Только актуальные объекты на сайте", "/realty/"},
			{"Новостройки", "Все ЖК на одном сайте. Цены и планировки.", "/zastr/"},
			{"Загородка", "Дома, дачи, коттеджи, участки", "/realty_out/"},
			{"Покупка без риска", "Возвращаем деньги из собственного фонда", "/legal_protection/"},
			{"Отзывы", "96% клиентов довольны нашими специалистами", "/feedback/"},
			{"Контакты", "Контактная информация", "/contacts/"},
			{"О компании", "«Этажи» — лидер рынка недвижимости", "/about/"},
			{"Стоимость услуг", "Оплата только после совершения сделки", "/price-buy/"},
		}},
	},
}

// Semantic clusters by theme.
var semanticClusters = map[string]semanticCluster{
	"вторичка": {
		Theme: "Вторичка (покупатель)",
		Modifiers: []string{
			"купить", "недорого", "без посредников", "авито", "циан", "домклик",
			"покупка", "цена", "продажа", "стоимость", "от хозяина", "объявления", "дешевая",
		},
		Objects: []string{
			"квартира", "однушка", "двушка", "трешка", "студия квартира", "вторичка",
			"1 комнатная", "однокомнатная", "2 комнатная", "двухкомнатная",
			"3 комнатная", "трехкомнатная",
		},
		NegativeKw: []string{
			"снять", "сдам", "сниму", "сдаю", "аренда", "арендовать",
			"сутки", "посуточно", "суточно", "помесячно", "длительный",
			"бесплатно", "ремонт", "кадастровые", "оценка",
			"строить", "построить", "проект", "дни", "отопление", "ключ",
			"судебный", "почему", "как", "отзывы", "обустроить",
		},
		Notes: "Комбинируй {модификатор} + {объект} + {город}. Последние 5 минус-слов (москва, спб...) — убирать если кампания на этот город.",
	},
	"вторичка_продавец": {
		Theme: "Вторичка (продавец)",
		ExtraKeys: []string{
			"продать квартиру {город}", "оценить квартиру {город}",
			"сколько стоит квартира {город}", "помощь в продаже квартиры {город}",
			"быстро продать квартиру {город}", "агентство для продажи квартиры {город}",
		},
		NegativeKw: []string{"купить", "аренда", "снять", "новостройка"},
	},
	"загородка": {
		Theme: "Загородка (покупатель)",
		Modifiers: []string{
			"купить", "недорого", "без посредников", "авито", "циан", "домклик",
			"покупка", "цена", "продажа", "стоимость", "от хозяина", "объявления",
			"дешевый", "недвижимость",
		},
		Objects: []string{"дом", "коттедж", "дача", "участок", "земельный участок"},
		ExtraKeys: []string{
			"дача участок", "дом участок", "ижс участок",
			"дача земельный участок", "дом земельный участок", "ижс земельный участок",
		},
		NegativeKw: []string{
			"дракон", "снять", "сдам", "сниму", "сдаю", "аренда", "арендовать",
			"сутки", "посуточно", "бесплатно", "длительный", "ремонт",
			"кадастровые", "оценка", "строить", "построить", "постройка", "проект",
			"дни", "отопление", "ключ", "судебный", "суточно", "почему", "как", "отзывы",
			"помесячно",
		},
	},
	"новостройки": {
		Theme: "Новостройки (покупатель)",
		Modifiers: []string{
			"купить", "покупка", "цена", "стоимость", "без посредников", "продажа", "объявления",
		},
		Objects: []string{
			"новостройки", "жк", "жилой комплекс", "от застройщика",
			"однокомнатные", "1 комнатные", "двухкомнатные", "2 комнатные",
			"трехкомнатные", "3 комнатные", "квартира",
		},
		ExtraKeys: []string{
			"купить новостройку", "приобрести новостройку",
			"купить первичку", "квартира новостройки",
			"квартира от застройщика",
		},
		NegativeKw: []string{
			"бесплатно", "построить", "почему", "как", "отзывы",
			"помесячно", "обустроить", "рейтинг", "топ",
		},
	},
	"ипотека": {
		Theme: "Ипотека",
		Modifiers: []string{
			"рассчитать", "калькулятор", "взять", "подобрать", "заявка", "оформить",
			"банки", "онлайн", "условия",
			"сбер", "сбербанк", "втб", "газпром", "газпромбанк", "открытие", "дом рф", "этажи",
		},
		Objects: []string{
			"ипотека", "ипотечные ставки", "ипотечные программы",
			"ипотечный кредит", "ипотечный",
		},
		ExtraKeys: []string{
			"ипотека на строительство", "ипотека на вторичку", "ипотека на новостройки",
			"кредит на покупку жилья", "кредит купить квартиру",
		},
		NegativeKw: []string{
			"топ", "долг", "отказали", "обременение", "риск", "плюс", "минус",
			"развод", "формула", "порядок", "обязательства", "инструкция",
			"погашение", "почему", "как",
		},
	},
	"аренда": {
		Theme: "Аренда жилая",
		ExtraKeys: []string{
			"снять квартиру", "аренда квартир", "аренда квартиры на длительный срок",
			"аренда от собственника", "аренда без посредников",
			"снять в аренду", "аренда недвижимости", "аренда на длительный срок",
			"аренда комнаты", "аренда жилья", "арендовать квартиру",
		},
		NegativeKw: []string{
			"авто", "заключенных", "сутки", "договор", "места", "без водителя",
			"машина", "автомобиль", "условия", "образец", "посуточно", "суточно",
			"погрузчика", "экскаватора", "с выкупом",
		},
	},
	"коммерческая": {
		Theme: "Коммерческая недвижимость (покупка)",
		ExtraKeys: []string{
			"купить офис {город}", "коммерческая недвижимость {город}",
			"торговое помещение {город}", "купить склад {город}",
			"помещение под бизнес {город}", "производственное помещение {город}",
		},
		NegativeKw: []string{"жилая", "квартира", "дом", "дача"},
	},
	"бренд": {
		Theme: "Бренд (агентство)",
		ExtraKeys: []string{
			"этажи {город}", "АН Этажи", "этажи агентство недвижимости",
			"этажи официальный сайт", "этажи купить квартиру",
			"этажи недвижимость", "сайт этажи", "агентство этажи",
			"этажи ипотека", "этажи вторичка", "этажи дом",
		},
		NegativeKw: []string{"этаж здания", "этажность", "многоэтажный"},
	},
	"hr": {
		Theme: "HR (набор сотрудников)",
		ExtraKeys: []string{
			"работа риэлтором {город}", "вакансии этажи {город}",
			"работа в агентстве недвижимости {город}",
			"вакансия риэлтор {город}", "работа в недвижимости {город}",
		},
		NegativeKw: []string{"отзывы сотрудников", "зарплата", "жалоба"},
	},
}
